--系统常量配置



-- 所有 程序中用到的文字
--LANGUAGE 全局变量 

GameString = {
	Cn = {
        TOWERDESC = "是否花费10魔石购买50回合？",
		INPUTERRORTIME = "兑换码不正确,您还有%d次输入机会",
		ZFBZ = "战魂点不足，可在副本、精英副本、boss挑战模式中击杀BOSS获得战魂",
		ZFBZ2 = "战魂点不足",
		ROLEUPSSUCCESS = "潜能升级成功",
		ROLEUPFAIL = "潜能升级失败",
		FULL = "已满",
		LEVEL_COPY = "确定现在结束战斗，离开%s挑战？",
		PUBLIC_POWER_LIMIT = "溢出体力已到达上限",
		Copy_Life_Per = "生命不低于%s%%过关可获得1颗星",
		Copy_Round_Per = "%s回合内过关可获得1颗星",
		Public_Military_NotFit = "军衔不符",
		Public_Military_AlreadyGet = "已领取",
		Public_Military_MayGet = "可领取",
		Public_lel = "%d级",
		Public_invite_lel = "邀请好友一起来萌兽世界即可领取礼包！",
		Public_invite_help_Reward_send = "请求已发送，记得来领取帮助奖励",
		Public_invite_No_Break = "您的好友在十天内登录过游戏，无法断绝关系",
		Public_invite_Code_wrong = "您输入的验证码不存在",
		Public_invite_break_tip = "是否断绝关系",
		Public_CurLel = "当前等级：",
		Public_getReward_invite = "当好友达到一定等级时，即可领取丰厚的奖励",
		Public_invite_text = "小伙伴已经进入萌兽的世界，要去帮帮他吗",
		Public_invite_go = "立即前往",
		Public_invite_later = "添加好友",
		Public_invite_get_code = "您获得的邀请码为：%s",
		Public_invite_help_send = "您的帮助已发送",
		Public_invite_open ="%d级开启",
		Public_invite_addFriend = "验证成功，获得修行礼包。是否添加此人为好友？",
		Public_invite_success = "验证战友成功，获得修行礼包。",
		Public_invite_copy = "复制",
		Public_invite_copy_succ = "复制成功，可以分享给其他好友",
		Public_invite_copy_Fail = "复制失败，请自行输入",
		Public_invite_text1 = "邀请好友一起来萌兽世界即可领取礼包",
		Public_invite_text2 = "点击邀请码进行复制哦",
		Public_invite_text3 = "点击输入邀请码",
		Public_invite_verify_success = "邀请码验证成功",
		Public_invite_verify_fail = "验证失败",
		Public_job ="职业：%s",
		Public_Boss_Buy = "您已成功购买一个召唤石",
		Public_Info_star = "%d星",
		Public_input_name = "请输入角色名",
		
		
		Public_talent_copy = "当潜能到达%s既可解锁该层天赋",
		Public_talent_copy_no = "三选一，点击激活你想使用的天赋",
		Public_talent_maxLel = "最高可升至%d级",
		Public_talent_lelup = "升级成功",
		Public_talent_reset = "%d个小时",
		Public_talent_reset_success = "重置成功",
		Public_talent_active_success = "激活成功",
		Public_talent_layer = "第\n%d\n层",
		Public_talent_click_lelUp ="点击升级",
		Public_talent_click_noActive = "未激活",
		Public_talent_click_Active = "点击激活",
		Public_talent_click_Full = "已满级",
		
		Public_recharge_str1 = "充%d魔石",
		Public_recharge_str2 = "%d魔石",
		Public_recharge_str3 = "%d魔石立即到账",
		Public_recharge_str4 = "每天领取%d魔石",
		Public_recharge_str5 = "请先前往充值",
		
		Public_Mode_Pub = "普通关卡",
		Public_Mode_TuiTa = "推塔",
		Public_Mode_JJC = "竞技场",
		Public_Mode_JJC_Train ="训练赛",
		Public_Mode_JJC_TianTiSai = "天梯赛",
		Public_Mode_ActivityCopy = "活动副本",
		
		Physical_strength = "体力值",
		BuyPp = "是否花费%s魔石补充%d体力？",
        BuyPp2 ="体力不足，是否花费%s魔石补充60体力？",
		Ppfull="当前体力值已满",
		ATK = "攻击：%d",
		DEF = "防御：%d",
		Hit = "命中：%d",
		CRI = "暴击：%d",
		buyTime = "剩余购买次数：%d次\n\n确定花费%d个魔石购买推塔次数吗？",
		buyLife = "确实花费%d个魔石购买第%d次复活吗",
		sure = "确定",
		cancle = "取消",
		Profession = "职业",
		Buy = "购买",
		Bind_0 = "未绑定",
		Bind_1 = "已绑定",
		sell = "出售",
		resolve = "分解",
		hasPass = "已通关",
		TurnCard = "花费%d个魔石可以再翻开一张卡牌",
		getExp = "你获得%d经验",
		getCoin = "你获得[金币x%d]",
		getItem = "你获得[%s]",
		getBossStone = "成功领取了%d召唤石",
		BuyBossStone = "剩余购买次数：%d次\n\n要花费%d魔石购买召唤石吗？",
		ENTER_SWEEP = "要花费一张扫荡卡进行扫荡么？",
		ThreeStar_Sweep = "获得三星才可进行扫荡",
		Sweep_Card_BZ = "扫荡卡不足",
		-- 竞技场
		GameRank_BUY_TIMES = "剩余购买次数：%d次\n\n确定花费%d个魔石购买挑战次数吗?",
		GameRank_MSG_TIPS1 = "%s 挑战你, 对方%s",
		GameRank_MSG_TIPS2 = "你挑战 %s, 你%s",
		GameRank_MSG_SUCESS = "成功了！",
		GameRank_MSG_SUCESS1 = "胜利了！",
		GameRank_MSG_FAIL = "失败了！",	
		GameRank_MSG_RISE = "排名升至 %d！",
		GameRank_MSG_DROP = "排名降至 %d！",		
		GameRank_MSG_CLICK = "不能选择自己作为挑战对象！",
		GameRank_MSG_REWARD = "前%d名玩家可领取奖励",
		GameRank_MSG_DATE = "时间冷却中！",
		GameRank_MSG_PM = "排名 %d",
		GameRank_MSG_GETSCORE = "成功领取战绩 %d",		
		-- 援军
		Assistance_str_01 = "请选择一个援军",
		Assistance_str_03 = "刷新功能还未冷却，你可以使用1个魔石来刷新列表",
		Assistance_str_04 = "你要添加\"%s\"为好友吗？",
		Assistance_str_05 = "确定要刷新援军列表吗？";
		-- 商城
		ShopMall_BUY_TIPS = "确定花费%d个魔石购买%s?",
		ShopMall_BUY1_TIPS = "确定花费%d个金币购买%s?",
		ShopMall_BUYSCORE_TIPS = "确定花费%d战绩购买%s?",
		ShopMall_LIMITS_TIPS = "今日购买次数已经达到上限！",
		ShopMall_MISOSHU = "描述: %s",
		ShopMall_OPEN_VIP = "开通vip",
		ShopMall_INPUT_MAXNUM = "输入的数量需在1到%d之间！",
		ShopMall_INPUT_NUM = "该商品今日还可以购买%d次！",
		ShopMall_INPUT_RIGHT = "请输入正确数量！",
		ShopMall_PUR_GET = "获得【%sx%d】",
		ShopMall_TIPS_JF_FAIL = "购买失败, 战绩不足！",
		ShopMall_TIPS_YB_FAIL = "购买失败, 挑战者硬币不足！",
		ShopMall_TIPS_JB_FAIL = "购买失败, 金币不足！",
		ShopMall_TIPS_MS_FAIL = "购买失败, 魔石不足！",
		ShopMall_Cost_JB = "消耗金币：%s",
		ShopMall_Cost_MS = "消耗魔石：%s",
		ShopMall_Cost_ZJ = "消耗战绩：%s",
		ShopMall_Group = "%s(组)",
		
		-- 游戏设置
		Setup_EXIT_TIPS = "确定退出游戏吗 ！",
		Setup_CHANGE_ROLE_TIPS = "确定更换角色吗 ！",
		Setup_CHANGE_ACCOUNT_TIPS = "确定更换账号吗 ！",
		-- 排行榜
		Game_Rank_Lists_t1 = "排名",
		Game_Rank_Lists_t2 = "玩家昵称",
		Game_Rank_Lists_t3 = "等级",
		Game_Rank_Lists_t4 = "职业",
		Game_Rank_Lists_t5 = "战力",
		Game_Rank_Lists_t6 = "副本",
		-- 训练赛
		GAMETRAIN_PUR_TIMES = "剩余购买次数：%d次\n\n确定花费%d魔石购买挑战次数？",
		GAMETRAIN_PUR_REF = "确定花费%d魔石刷新挑战列表！",
		GAMETRAIN_PUR_LAST = "挑战次数不足！",
		-- 锻造
		EQUIPTRAIN_BROKEN_TIPS = "确定将该件装备分解成材料吗！",
		EQUIPTRAIN_CANNOT_BROKEN_TIPS = "该件物品无法分解！",
		EQUIPTRAIN_FAIL_BROKEN_TIPS = "分解失败！",
		EQUIPTRAIN_FAIL1_CANNOT_ADVANCE_TIPS = "该装备不能晋阶！",
		EQUIPTRAIN_FAIL_CANNOT_ADVANCE_TIPS = "晋阶需先将装备强化至满级！",
		EQUIPTRAIN_FAIL_NOT_MATERIAL_TIPS = "所需材料不足,无法晋阶！",
		EQUIPTRAIN_SUCCESS_TIPS = "晋阶成功！",
		EQUIPTRAIN_FAIL1_NOT_MATERIAL_TIPS = "所需材料不足,无法重铸！",
		EQUIPTRAIN_FAIL_CANNOT_RECAST_TIPS = "该件装备无法重铸！",
		EQUIPTRAIN_SUCCESS1_TIPS = "重铸成功！",
		EQUIPTRAIN_FAIL2_TIPS = "装备中的物品无法分解",
		EQUIPTRAIN_PUTON_RESLOVE_FAIL_TIPS = "已经装备,无法分解!",
		EQUIPTRAIN_SELECT_EQU_PLEASE_TIPS = "请选择要分解的装备!",
		EQUIPTRAIN_RECAST_FIRST_TIPS = "请先重铸!",
		EQUIPTRAIN_RECAST_STRENSCUS_TIPS = "强化成功",
		EQUIPTRAIN_EQUIP_NOT_SAVE_TIPS = "当前重铸未保存,是否要退出!",
		EQUIPTRAIN_STR_01 = "所需材料不足,无法转换！",
		EQUIPTRAIN_STR_02 = "该装备无法转换！",
		EQUIPTRAIN_STR_03 = "转换成功，你获得了\"%s\"",
		EQUIPTRAIN_STR_04 = "该件装备带有宝石，是否分解？（分解后宝石将返还）",
		EQUIPTRAIN_STR_05 = "该件装备带有宝石，是否出售？（宝石将一起出售）",
		EQUIPTRAIN_STR_06 = "出售该物品将获得%d金币，是否进行出售？",
		EQUIPTRAIN_GET_01 = "(副本掉落获得)",
		EQUIPTRAIN_GET_02 = "（通过竞技兑换获得）",
		EQUIPTRAIN_GET_03 = "（充值成为vip即可领取）",
		
		-- public
		Public_ZL_VAL = "战力: %d", 
		Public_DJ_VAL = "等级: %d", 
		Public_PM_VAL = "排名: %d",
		Public_JF_VAL = "战绩: %d",
		Public_ZJ = "战绩",
		Public_MSG_PUR_FAIL = "购买失败！",	
		Public_MSG_PUR_SUCC = "购买成功！",	
		Public_BTN_PUR = "购 买",
		Public_NOT_OPEN = "功能未开放 ！",		
		Public_CLOTHES_COLOR_W = "白装",	
		Public_CLOTHES_COLOR_G = "绿装",	
		Public_CLOTHES_COLOR_B = "蓝装",	
		Public_CLOTHES_COLOR_P = "紫装",	
		Public_CLOTHES_COLOR_O = "橙色装",	
		Public_MSBZ = "魔石不足！",	
		Public_JBBZ = "金币不足！",
		Public_JFBZ = "战绩不足！",
		Public_Power_BZ = "体力不足",
		Public_OpenLevel = "%d级才开放",
		Public_Level_Gift = "%d级礼包",
		Public_Get_Reward = "领取奖励",
		Public_Refresh_List = "刷新列表",
		Public_Alchemoy_Time_Out = "今日炼金次数已用完，请明日再来",
		Public_Alchemoy_Exp_Not_Enough = "领取失败，炼金经验不足",
		Public_Alchemoy_Received = "领取失败，该奖励今日已领取过了",
		Public_Alchemoy_Success = "炼金成功",
		Public_Alchemoy_Need_Exp = "需要%d经验",
		Public_BuyTimes_Not_Enough = "今日购买次数已用光！",
		Public_Normal_Price = "原价：",
		Public_Spe_Price = "折扣价：",
		Public_Limit_Buy_Times = "限量购买%s份",
		Public_Pass_Copy = "通过第%d章【%s】副本才能开启",
		Public_buy_getSpeCoin = "是否花费%s魔石进行高级炼金？",
		Public_Tower = "魔塔",
		Public_Sweep = "扫荡\"%s\"",
		
		ATK5 = "攻击：",
		LIF5 = "生命：",
		SPE5 = "速度：",
		HIT5 = "命中：",
		CRT5 = "暴击：",
		MIS5 = "闪避：",
		RXP5 = "韧性：",
		-- 通用中文符号
		PUBLIC_L_BRACKET = "（",
		PUBLIC_R_BRACKET = "）",
		PUBLIC_LM_BRACKET = "【",
		PUBLIC_RM_BRACKET = "】",
		PUBLIC_COMMA = "、",
		PUBLIC_COLON = "：",
		-- 通用中文术语,单词
		PUBLIC_GOLD = "金币",
		PUBLIC_GEM = "宝石",
		PUBLIC_EXP = "经验",
		PUBLIC_HP = "体力",
		PUBLIC_COMBAT_GAINS = "战绩",
		PUBLIC_HONOR = "荣誉",
		PUBLIC_MAGIC_STONE = "魔石",
		PUBLIC_SUMMON_STONE = "召唤石",
		PUBLIC_HP_DRUG = "体力",	-- 可溢出体力药剂
		PUBLIC_SCORE = "积分",
		PUBLIC_RUNE = "符文",
		PUBLIC_RUNE_CHIP = "符文碎片",
		PUBLIC_LING_QU = "领取",
		PUBLIC_KE_LING_QU = "可领取",
		PUBLIC_BU_KE_LING_QU = "不可领取",
		PUBLIC_YI_LING_QU = "已领取",
		PUBLIC_WEI_LING_QU = "未领取",
		PUBLIC_WAN_CHENG = "完成",
		PUBLIC_YI_WAN_CHENG = "已完成",
		PUBLIC_WEI_WAN_CHENG = "未完成",
		PUBLIC_NONE = "无",
		PUBLIC_LIFE = "生命",
		PUBLIC_ATTACK = "攻击",
		PUBLIC_SPEED = "速度",
		PUBLIC_HIT = "命中",
		PUBLIC_CRITICAL = "暴击",
		PUBLIC_MISS = "闪避",
		PUBLIC_TENACITY = "韧性",
		PUBLIC_RMB = "元",
		PUBLIC_ZH = "战魂",
		PUBLIC_HUO_DE = "获得",
		PUBLIC_TIAN = "天",
		PUBLIC_JINBI_BUZU = "金币不足",
		PUBLIC_BAI = "白",
		PUBLIC_LV = "绿",
		PUBLIC_LAN = "蓝",
		PUBLIC_ZI = "紫",
		PUBLIC_CHENG = "橙",
		PUBLIC_HONG = "红",
		PUBLIC_CHONG_ZHI = "充值",
		
		PUBLIC_GOLD_MONST = "金冠怪",
		PUBLIC_SILVER_MONST = "银冠怪",
		PUBLIC_ACTIVE_MONST = "主动怪",
		PUBLIC_COMMON_MONST = "普通怪",
		PUBLIC_ENEMY = "敌人",
		PUBLIC_COST_POWER = "花费体力：%s",
		PUBLIC_LEAVE_TIP = "你还未击杀该层所有怪物,如果离开将会失去三星奖励机会,是否继续?",
		PUBLIC_NEW_GUIDE = "新手引导关",
		PUBLIC_ATTACK_ACTIVE = "主动攻击" ,
		PUBLIC_ATTACK_NOACTIVE = "被动攻击",
		
		
		--战斗
		TASK_STR_01 = "需要等级Lv%d",
		TASK_STR_02 = "（已完成）",
		
		COPY_LOCK = "副本尚未开启。请先完成前一个副本和对应的主线副本。",		
		LEVEL = "等级:%d",
		COST_EMONY = "花费%d个",
	
		--出售
		Sell_eror_1 = "出售数量必须大于0",
		Sell_eror_2 = "输入数值错误",
		
		--背包
		Bag_name_1 = "背包",
		Bag_name_2 = "我的宝石",
		Bag_name_3 = "我的符文",
		
		Bag_tag_11 = "类型",
		Bag_tag_12 = "品质",
		Bag_tag_13 = "等级",
		Bag_tag_14 = "售价",
		
		Bag_tag_21 = "等级",
		Bag_tag_22 = "类型",
		Bag_tag_23 = "售价",
		
		Bag_tag_31 = "装备",
		Bag_tag_32 = "符文",
		Bag_tag_33 = "宝石材料",
		Bag_tag_34 = "全部",
		
		Bag_extend = "是否拓展背包",
		Bag_extend_1 = "当前背包已满，是否拓展背包",
		Bag_extend_ok = "拓展背包",
		Bag_extend_win = "背包扩充成功,背包容量增加%d格",
		
		Bag_unload_equip = "确定卸下装备吗？卸下装备时，该装备的宝石会返回到背包",
		Bag_change_equip = "确定更换装备吗？更换装备时，该装备的宝石会返回到背包",
		
		--装备
		EQUIP_HIT_RATIO = "精准之",
		EQUIP_MISS_RATIO = "灵巧之",
		EQUIP_CRITICAL_RATIO = "残暴之",
		EQUIP_TENACITY = "坚韧之",
		EQUIP_SPEED = "疾风之",
		EQUIP_LIFE = "生命之",
		EQUIP_ATK = "凶猛之",
		Equip_strengthen = "%s(强化+%s)",
		Equip_STR_01 = "该物品与你的职业不符，无法装备",
		Equip_STR_02 = "等级不足，无法装备",
		Equip_STR_03 = "强化+",
		Equip_STR_04 = "装备强化成功",
		Equip_STR_05 = "这个操作将会直接把装备升至满级，同时消耗大量金币，确定要继续吗？",
		Equip_STR_06 = "本次操作完成%d次强化\n成功：%d次    失败：%d次\n总花费：%d金币",
		--宝石
		Gem_hint_1 = "背包中没有保护符,是否前往购买保护符",
		Gem_hint_2 = "合成失败,毁坏%d颗宝石",
		Gem_hint_3 = "合成所需宝石数量不足",
		Gem_hint_4 = "当前宝石已经是最高级",
		Gem_hint_5 = "金币不足",
		Gem_hint_6 = "需要%sX5",
		Gem_hint_7 = "成功率:%d%%",
		Gem_hint_8 = "合成成功,获得了%d个%s",
		Gem_hint_9 = "不使用保护符保护宝石，将可能在合成失败时导致低级宝石消失。确定不使用保护符吗？",
		--好友
		InputFriName  = "请输入好友的名字",
		YouFriCountExc = "您的好友个数已经达到上线",
		NoChatToOffline = "该好友不在线,不能发送聊天信息",
		InputChatContent = "请输入要发送的内容",
		NoExceThirty = "不能超过30个字",
		FriendName = "和%s的聊天",
		DeleFriend = "确定删除该好友？",
		AddFriSucess = "添加好友成功",
		AddSomeFriSuc = "添加好友【%s】成功",
		DeleFriSuc = "删除好友成功",
		DeleteSomeFri = "%s已将您删除",
		IsFriAlready = "对方已经是您的好友",
		ReqFriSendAlre = "您的好友请求已经发送",
		OfflineNoAdd = "该角色不在线，不能添加其为好友",
		NoAddYou = "不能添加自己为好友",
		NoRoleName = "该角色不存在",
		SearFriErr = "搜索好友有错误",
		DeleFriFail = "删除好友失败",
		DeleFriErr = "删除好友出错",
		ReqSendSuc = "好友请求发送成功",
		ReqSendFai = "好友请求发送失败",
		reqSendErr = "请求添加对方为好友发送出错",
		RefuAddFri = "对方拒绝添加你为好友",
		SendChatErr = "发送聊天数据出错",
		DeleteFriend = "删除好友",
		Chat = "聊天",
		Agree = "同意",
		Refuse = "拒绝",
		AddFriend = "加为好友",
		Friend_Send_Hp = "赠送给好友的体力已送出",
		Friend_Get_Hp = "已获得好友赠送的%d点体力成功",
		Friend_send_Num = "(%d点体力)",
		
		--登录
		InputAccOrPass ="请输入用户名或密码",
		SelectPro  = "请勾选用户协议",
		PassNoSame = "两次密码不匹配",
		AccAndPassNOSame = "账号和密码不允许相同",
		AccountFormat = "账号为5到11位字母和数字的组合，首字符为字母",
		PasswordFormat = "密码为5到11位字母和数字的组合",
		OnlyLetAndNum = "只能输入数字或字母",
		InputAccount = "请输入账号",
		InputPass = "请输入密码",
		InputPassAgain = "请再次输入密码",
		LimitEleven = "长度上限11",
		MaxRoles = "您的角色个数已达上限",
		RegisSuc = "注册成功",
		DeleteRole = "确定要删除该角色吗？",
		RecoverInfo = "该角色7天内可花费%s魔石复原",
		MoneyNotEnough ="魔石不足",
		CreateRole = "请创建角色",
		DeleteRole = "角色将被删除",
		RecverSuccess = "复原角色成功",
		--每日奖励
		DAILY_AWARD_STR_01 = "每日礼包包含：",
		DAILY_AWARD_STR_02 = "%d日礼包包含：",
		DAILY_AWARD_STR_03 = "不可领取",
		DAILY_AWARD_STR_04 = "已领取",
		DAILY_AWARD_STR_05 = "可领取",
		DAILY_AWARD_STR_06 = "小贴士：每日礼包没有及时领取，将不计算累计天数，无法领取奖励哦！",
		DAILY_AWARD_STR_08 = "扫荡卡x10",
		-- GM
		GM_ItemIdError = "您输入的物品ID有误",
		GM_SculpIdError = "您输入的符文ID有误",
		--NET
		NETWORK_STR_01 = "网络异常，建议确认网络畅通后重试",
		NETWORK_STR_02 = "重新连接成功",
		NETWORK_STR_03 = "服务端出现异常，请重新进入",
		NETWORK_STR_04 = "该账号在其他地方登录",
		NETWORK_STR_05 = "客户端与服务端版本不一致",
		NETWORK_STR_06 = "登录校验失败",
		NETWORK_STR_07 = "请退出游戏再重新进入",
		NETWORK_STR_08 = "获取服务器列表失败，请在网络环境良好的情况下重新登录",
		--祝福
		BLESS_Already_Active = "该祝福已激活过了",
		BLESS_Emoney_notEnough = "魔石不足，前去充值",
		BLESS_TIP_1 = "是否花费%d魔石来激活祝福",
		BLESS_Cover = "是否花费%d魔石来激活新的祝福，旧的祝福效果将被覆盖",
		BLESS_Coin_notEnough = "金币不足",
		BLESS_Active = "激活",
		BLESS_No_Active = "已激活",
		BLESS_STR_01 = "持续%d小时",
		BLESS_STR_02 = "剩余时间：%s",
		-- 技能
		SKILL_TYPE_01 = "单体伤害",
		SKILL_TYPE_02 = "群体伤害",
		SKILL_TYPE_03 = "恢复",
		SKILL_TYPE_04 = "持续伤害",
		SKILL_TYPE_05 = "持续恢复",
		SKILL_TYPE_06 = "控制",
		SKILL_TYPE_07 = "增益",
		SKILL_TYPE_08 = "减益",
		SKILL_TYPE_09 = "群体控制",
		SKILL_TYPE_10 = "减少伤害",
		SKILL_TYPE_11 = "吸血",
		SKILL_TYPE_12 = "驱散状态",
        SKILL_TYPE_13 = "反弹伤害",
		SKILL_TYPE_14 = "召唤仆从",
		SKILL_STR_01 = "回合",
		SKILL_STR_02 = "解锁该技能需要%d个（%s）碎片",
		SKILL_STR_03 = "提升品质需要%d个（%s）碎片",
		SKILL_STR_04 = "技能等级已达上限",
		SKILL_STR_05 = "已达最高品质，无需晋阶",
		SKILL_STR_06 = "技能碎片不足，使用【召唤】能获取更多的技能碎片",
		SKILL_STR_07 = "技能解锁成功",
		SKILL_STR_08 = "技能装备成功",
		SKILL_STR_09 = "技能卸下成功",
		SKILL_STR_10 = "技能方案改变成功",
		SKILL_STR_11 = "点击解锁",
		SKILL_STR_12 = "点击晋阶",
		SKILL_STR_13 = "材料不足",
		SKILL_STR_14 = "技能等级不能超过角色等级！",
		-- 活跃度
		ACTIVENESS_STR_01 = "完成度",
		ACTIVENESS_STR_02 = "每次奖励",
		ACTIVENESS_STR_03 = "%d活跃礼包：",
		-- 背包
		BAG_STR_01 = "未选择物品",
		BAG_STR_02 = "未选择装备",
		BAG_STR_03 = "成功售出,获得%d个金币",
		BAG_STR_04 = "宝石镶嵌成功",
		BAG_STR_05 = "宝石卸下成功",
		BAG_STR_06 = "是否花费%d魔石卸下宝石",
		BAG_STR_07 = "是否确定出售物品",
		ACTIVITY_STR_01 = "等待开启",
		-- 升阶
		OPEN_POTENT = "需要等级Lv%d才开启",
		SYSTEM_STR_01 = "系统出错：code=%d，sys_msg=%s",
		EMAIL_STR_01 = "邮件已到期，不能领取",
		ROLE_CREATE_STR_01 = "角色名称不能超过6个字数",
		
		-- 掉落概率
		DROP_RATE = "掉落概率：%s",
		VERY_LOW = "极低",
		LOW = "低",
		MID = "中",
		HIGH = "高",
		ACTIVITY_COPY_STR_01 = "角色达到%d级开启",
		ACTIVITY_COPY_STR_02 = "今日剩余挑战次数不足，明日再来吧",
		
		-- 聊天信息
		WORLD_CHAT_ERROR_1 = "发送聊天内容不能为空",
		WORLD_CHAT_ERROR_2 = "聊天内容不能超过30个字符",
		WORLD_CHAT_ERROR_3 = "发言太快了，休息一下",
		WORLD_CHAT_ERROR_4 = "您被GM禁言了，请联系GM",
		REMAINTIMES = "剩余%d次",
		BLOCKROLE = "要暂时屏蔽此玩家？\n（重新登录游戏时，自动解除）",
		TIMESUP = "每日免费信息已用完，是否花费%d魔石，购买%d条信息",
		CHAT_SYSTEM = "【系统】",
		CHAT_NOTICE = "【公告】",
		
		-- 聊天界面系统公告
		SYSTEM_MSG_1 = "【系统】请使用文明语言，违者将按照相应条款进行处罚",
		SYSTEM_MSG_2 = "【系统】严禁帐号买卖行为，非官方渠道买卖道具将永久封号",
		SYSTEM_MSG_3 = "【系统】频道内点击玩家昵称，可以选择屏蔽刷屏广告",
		
		-- 兑换码
		ACTIVAL_REWARD_ERROR_1 = "请输入兑换码",
		
		-- 一键补齐
		ONE_KEY_BUY_ALL = "确定花费%d个魔石补齐材料?",
		-- 新手引导标题
		GUIDE_TITLE_01 = "装备强化",
		GUIDE_TITLE_02 = "使用援军",
		GUIDE_TITLE_03 = "提升潜能",
		GUIDE_TITLE_04 = "挑战精英副本",
		GUIDE_TITLE_05 = "符文占卜和符文升级",
		GUIDE_TITLE_06 = "挑战BOSS",
		GUIDE_TITLE_07 = "挑战魔塔",
		GUIDE_TITLE_08 = "挑战训练赛",
		GUIDE_TITLE_09 = "挑战分组赛",
		GUIDE_TITLE_10 = "挑战排位赛",
		GUIDE_TITLE_11 = "自动战斗",
		GUIDE_TITLE_12 = "技能升级",
		GUIDE_TITLE_13 = "技能晋阶",
		GUIDE_TITLE_14 = "英雄天赋",
		GUIDE_TITLE_15 = "装备晋阶",
		GUIDE_TITLE_16 = "宝石镶嵌",
		-- 召唤
		RUNE_FOR_FREE = "免费",
		RUNE_NORMAL_CD = "后免费",
		RUNE_FREE_TIMES = "免费次数：%d/%d",
		RUNE_NORMAL_PAY_ONE = "是否花费%d金币进行单次普通召唤",
		RUNE_NORMAL_PAY_TEN = "是否花费%d金币进行十次普通召唤",
		RUNE_SPECIAL_PAY_ONE = "是否花费%d魔石进行单次稀有召唤",
		RUNE_SPECIAL_PAY_TEN = "是否花费%d魔石进行十次稀有召唤",
		RUNE_TIPS_MS_FAIL = "魔石不足，召唤失败！",
		RUNE_TIPS_JB_FAIL = "金币不足，召唤失败！",
		RUNE_NORMAL_TEXT = "获得材料、宝石、技能碎片、天赋碎片、战魂。",
		RUNE_SPECIAL_TEXT = "获得材料、宝石、技能碎片、完整技能、天赋碎片、战魂。",
		RUNE_UNLOCK_SKILL_TIP_1 = "该技能已解锁，技能兑换为%s*%d",
		
		-- 物品产出关卡
		OUTPUT_COPY_NORMAL = "第%d章 %s副本",
		OUTPUT_COPY_SPECIAL = "第%d章 %s副本(精英)",
		OUTPUT_COPY_BOSS = "BOSS挑战 %s副本",
		OUTPUT_TIP_01 = "宝石合成",
		OUTPUT_TIP_02 = "装备分解",
		OUTPUT_TIP_03 = "该副本尚未解锁",
		-- 体力奖励
		POWER_PH_STR_01 = "每日%s至%s可领取%d体力",
		POWER_PH_STR_02 = "成功领取%d点体力",
		
		-- 公告提示
		NOTICE_SYSTEM_TIP_1 = "暂无系统公告",
		NOTICE_SYSTEM_TIP_2 = "该活动已关闭",
		NOTICE_SYSTEM_TIP_3 = "查看详情>>",
		
		-- 测试期间充值提示
		RECHARGE_TIP_1 = "封测期间不开放充值",
		
		-- 新分组赛
		GAME_MATCH_TIP_1 = "是否花费%d魔石进行全队回复",
		GAME_MATCH_TIP_2 = "是否花费%d魔石进行更换队友",
		GAME_MATCH_TIP_3 = "是否免费重置队友及关卡",
		GAME_MATCH_TIP_4 = "是否花费%d魔石进行重置队友及关卡",
		GAME_MATCH_TIP_5 = "免费%d次",
		GAME_MATCH_TIP_6 = "不需要回复生命",
		GAME_MATCH_TIP_7 = "点击【获取队友】凑齐队伍再进行挑战",
		GAME_MATCH_TIP_8 = "点击【获取队友】凑齐队伍再进行回复生命",
		GAME_MATCH_TIP_9 = "己方队伍全灭，点击【重置】，重新进行挑战",
		GAME_MATCH_TIP_10 = "敌方队伍全灭，点击【重置】，重新进行挑战",
		GAME_MATCH_TIP_11 = "是否免费进行全队回复",
		
		-- 新年活动
		SPRING_ACTIVITY_TIP_1 = "当前次数:%d",
		SPRING_ACTIVITY_TIP_2 = "%d年%d月%d日",
		SPRING_ACTIVITY_TIP_3 = "获得%s",
		SPRING_ACTIVITY_TIP_4 = "活动已结束",
		
		-- 新充值
		NEW_RECHARGE_TIP_1 = "是否花费%d魔石购买%d金币？",
		NEW_RECHARGE_TIP_2 = "是否花费%d魔石购买%sX%d？",
		NEW_RECHARGE_TIP_3 = "成功购买【%d金币】",
		GO_TO_PAY = "去支付",
		
		-- BUFF
		MONSTER_INFO_1 = "所剩回合：%d",
		MONSTER_INFO_2 = "目前没有受到任何状态的影响",
		
		-- 勋章
		GAME_MEDAL_TIP_1 = "勋章等级不能超过角色等级",
		GAME_MEDAL_TIP_2 = "战绩不足",
		GAME_MEDAL_TIP_3 = "请先装备饰品，饰品可在竞技场商城内购入",
	},
	En = {
		Physical_strength = "Physical_strength",
		BuyPp = "Buy physical yet? Today, you have to buy% d times",
		Ppfull="体力值已经满了",
		ATK = "ATK：%d",
	}
}

--获取当前 文字 支持 N个参数
function GameString.get(strkey,...)
	local s = GameString[LANGUAGE][strkey]
	local finals  = string.format(s,...)
	return finals
end
