--region EffectPVP33.lua
--Author : shenl
--Date   : 2015/1/5
EffectPVP33 = class(EffectPlayerCast)--构造function EffectPVP33:ctor()end--初始化function EffectPVP33:init()end--执行function EffectPVP33:play()	local function exitCB(sender)		sender:removeFromParentAndCleanup(true)		self:over()	end	local parent = EffectMgr.getConfig("emc_front_layer")		--背景遮罩	local mask = self:createMask()	parent:addChild(mask)	local arr = CCArray:create()	arr:addObject(CCDelayTime:create(2.5))	arr:addObject(CCCallFuncN:create(exitCB))	mask:runAction(CCSequence:create(arr))		--图层	local layer = CCLayer:create()	mask:addChild(layer, 1000)	layer:setPosition(ccp(0, 0))	--背景	local bg = CCSprite:create("match_enter_bg.png")	layer:addChild(bg)	bg:setPosition(ccp(320, 480))		local arr = CCArray:create()	arr:addObject(CCFadeIn:create(0.3))	arr:addObject(CCDelayTime:create(2.3))	bg:runAction(CCSequence:create(arr))		local filename1 = ModelPlayer.getRoleUpAppence(ModelPlayer.getRoleType(), ModelPlayer.getAdvancedLevel()).heroicon	    local friendlistInfo = FightConfig.getConfig("fc_jjc_friend_list")     --多人赛敌方列表
	local enemylistInfo = FightConfig.getConfig("fc_jjc_enemy_list")       --多人赛我方友军列表	    --友方	local player1 = CCSprite:create(filename1)	local size = player1:getContentSize()	layer:addChild(player1)	player1:setPosition(ccp(140 + 623, 524 -150))	local name1 = self:playerName(ModelPlayer.getNickName())	player1:addChild(name1)	name1:setPosition(ccp(size.width / 2, -20))		local arr1 = CCArray:create()	arr1:addObject(CCDelayTime:create(0.3))	arr1:addObject(CCMoveBy:create(0.3, ccp(-650, 0)))	arr1:addObject(CCMoveBy:create(0.1, ccp(27, 0)))	player1:runAction(CCSequence:create(arr1))	    --友军    for key,role_Info in pairs(friendlistInfo) do         local roleType = role_Info.type	    local level = role_Info.advanced_level	    local filename = ModelPlayer.getRoleUpAppence(roleType, level).heroicon	    local player = CCSprite:create(filename)	    layer:addChild(player)	    player:setPosition(ccp(140 + 623, 524 + (key-1)*150))	    local playerName = self:playerName(role_Info.nickname)	    player:addChild(playerName)	    playerName:setPosition(ccp(size.width / 2, -20))        local _arr = CCArray:create()	    _arr:addObject(CCDelayTime:create(0.3))	    _arr:addObject(CCMoveBy:create(0.3, ccp(-650, 0)))	    _arr:addObject(CCMoveBy:create(0.1, ccp(27, 0)))	    player:runAction(CCSequence:create(_arr))    end    --敌军    for key,role_Info in pairs(enemylistInfo) do         local roleType = role_Info.type	    local level = role_Info.advanced_level	    local filename2 = ModelPlayer.getRoleUpAppence(roleType, level).heroicon	    local player = CCSprite:create(filename2)	    layer:addChild(player)	    player:setPosition(ccp(-123, 524 + (key-2)*150))	    player:setFlipX(true)           	    local playerName = self:playerName(role_Info.nickname)	    player:addChild(playerName)	    playerName:setPosition(ccp(size.width / 2, -20))	       	    local arr2 = CCArray:create()	    arr2:addObject(CCDelayTime:create(0.3))	    arr2:addObject(CCMoveBy:create(0.3, ccp(650, 0)))	    arr2:addObject(CCMoveBy:create(0.1, ccp(-27, 0)))	    player:runAction(CCSequence:create(arr2))     end endfunction EffectPVP33:playerName(name)	local layer = CCLayer:create()	local color = ccc3(255, 255, 255)	local label = CommonFunc_createCCLabelTTF(ccp(0.5, 0.5), nil, nil, 19, color, name)	layer:addChild(label, 2)		local bg = CCScale9Sprite:create("monster_name_bg.png")	layer:addChild(bg)	local size = label:getContentSize()	size.width = size.width + 20	bg:setCapInsets(CCRectMake(11,11,11,11))	bg:setPreferredSize(size)	bg:setAnchorPoint(ccp(0.5,0.5))	return layerend



--endregion
