%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(rpc_types).

-include("rpc_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('attachment') ->
  {struct, [{1, i32},
          {2, i32}]}
;

struct_info('time_format') ->
  {struct, [{1, i16},
          {2, i16},
          {3, i16},
          {4, i16},
          {5, i16},
          {6, i16}]}
;

struct_info('role_info') ->
  {struct, [{1, i64},
          {2, i64},
          {3, i32},
          {4, string},
          {5, i16},
          {6, i32},
          {7, i32},
          {8, i32},
          {9, {struct, {'rpc_types', 'time_format'}}},
          {10, i16}]}
;

struct_info('notice_item') ->
  {struct, [{1, i32},
          {2, string},
          {3, string},
          {4, i32},
          {5, string},
          {6, i32},
          {7, i32},
          {8, {struct, {'rpc_types', 'time_format'}}},
          {9, {struct, {'rpc_types', 'time_format'}}},
          {10, i32},
          {11, {struct, {'rpc_types', 'time_format'}}},
          {12, i32}]}
;

struct_info('cDKey_reward_item') ->
  {struct, [{1, i32},
          {2, {list, i32}},
          {3, {list, i32}}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('attachment') ->
  {struct, [{1, required, i32, 'award_id', undefined},
          {2, required, i32, 'amount', undefined}]}
;

struct_info_ext('time_format') ->
  {struct, [{1, required, i16, 'year', 0},
          {2, required, i16, 'month', 0},
          {3, required, i16, 'day', 0},
          {4, required, i16, 'hour', 0},
          {5, required, i16, 'minute', 0},
          {6, required, i16, 'second', 0}]}
;

struct_info_ext('role_info') ->
  {struct, [{1, required, i64, 'user_id', 0},
          {2, required, i64, 'role_id', 0},
          {3, required, i32, 'role_status', 0},
          {4, required, string, 'nick_name', ""},
          {5, required, i16, 'level', 0},
          {6, required, i32, 'exp', 0},
          {7, required, i32, 'gold', 0},
          {8, required, i32, 'emoney', 0},
          {9, required, {struct, {'rpc_types', 'time_format'}}, 'create_time', #time_format{}},
          {10, required, i16, 'vip', 0}]}
;

struct_info_ext('notice_item') ->
  {struct, [{1, required, i32, 'id', 0},
          {2, required, string, 'title', ""},
          {3, required, string, 'sub_title', ""},
          {4, required, i32, 'icon', 0},
          {5, required, string, 'content', ""},
          {6, required, i32, 'toward_id', 0},
          {7, required, i32, 'mark_id', 0},
          {8, required, {struct, {'rpc_types', 'time_format'}}, 'start_time', #time_format{}},
          {9, required, {struct, {'rpc_types', 'time_format'}}, 'end_time', #time_format{}},
          {10, required, i32, 'priority', 0},
          {11, required, {struct, {'rpc_types', 'time_format'}}, 'create_time', #time_format{}},
          {12, required, i32, 'top_pic', 0}]}
;

struct_info_ext('cDKey_reward_item') ->
  {struct, [{1, required, i32, 'id', 0},
          {2, required, {list, i32}, 'reward_ids', []},
          {3, required, {list, i32}, 'reward_amounts', []}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

