%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(rpcService_thrift).
-behaviour(thrift_service).


-include("rpcService_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% convertCDKey(This, RoleId, GiftId)
function_info('convertCDKey', params_type) ->
  {struct, [{1, i64},
          {2, i32}]}
;
function_info('convertCDKey', reply_type) ->
  i32;
function_info('convertCDKey', exceptions) ->
  {struct, []}
;
% set_CDKey_reward_item(This, OptType, CDKeyItem)
function_info('set_CDKey_reward_item', params_type) ->
  {struct, [{1, i32},
          {2, {struct, {'rpc_types', 'cDKey_reward_item'}}}]}
;
function_info('set_CDKey_reward_item', reply_type) ->
  i32;
function_info('set_CDKey_reward_item', exceptions) ->
  {struct, []}
;
% sendEmail(This, Id, Title, Content, Attachments, EndTime, Type, RoleIds)
function_info('sendEmail', params_type) ->
  {struct, [{1, i32},
          {2, string},
          {3, string},
          {4, {list, {struct, {'rpc_types', 'attachment'}}}},
          {5, {struct, {'rpc_types', 'time_format'}}},
          {6, i16},
          {7, {list, i64}}]}
;
function_info('sendEmail', reply_type) ->
  i32;
function_info('sendEmail', exceptions) ->
  {struct, []}
;
% recharge(This, UserID, OrderID, Money, ProductID)
function_info('recharge', params_type) ->
  {struct, [{1, i64},
          {2, i64},
          {3, i32},
          {4, i32}]}
;
function_info('recharge', reply_type) ->
  i32;
function_info('recharge', exceptions) ->
  {struct, []}
;
% get_role_info_by_nickname(This, NickName)
function_info('get_role_info_by_nickname', params_type) ->
  {struct, [{1, string}]}
;
function_info('get_role_info_by_nickname', reply_type) ->
  {struct, {'rpc_types', 'role_info'}};
function_info('get_role_info_by_nickname', exceptions) ->
  {struct, []}
;
% modify_rolestatus_by_roleid(This, RoleId, RoleStatusType, OptType)
function_info('modify_rolestatus_by_roleid', params_type) ->
  {struct, [{1, i64},
          {2, i32},
          {3, i32}]}
;
function_info('modify_rolestatus_by_roleid', reply_type) ->
  i32;
function_info('modify_rolestatus_by_roleid', exceptions) ->
  {struct, []}
;
% get_online_role_amount(This)
function_info('get_online_role_amount', params_type) ->
  {struct, []}
;
function_info('get_online_role_amount', reply_type) ->
  i32;
function_info('get_online_role_amount', exceptions) ->
  {struct, []}
;
% broadcast_service_msg(This, Msg, RepeatTimes, Priority)
function_info('broadcast_service_msg', params_type) ->
  {struct, [{1, string},
          {2, i32},
          {3, i32}]}
;
function_info('broadcast_service_msg', reply_type) ->
  {struct, []};
function_info('broadcast_service_msg', exceptions) ->
  {struct, []}
;
% set_notice(This, OptType, NoticeInfo)
function_info('set_notice', params_type) ->
  {struct, [{1, i32},
          {2, {struct, {'rpc_types', 'notice_item'}}}]}
;
function_info('set_notice', reply_type) ->
  i32;
function_info('set_notice', exceptions) ->
  {struct, []}
;
% get_all_role_count(This)
function_info('get_all_role_count', params_type) ->
  {struct, []}
;
function_info('get_all_role_count', reply_type) ->
  i32;
function_info('get_all_role_count', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> no_function.

