require "Class"
require "String"
require "List"
require "VarHelper"
require "ClientDatabase"
require "Test"
require "CommonFunc"
require "UIEasyScrollView"
require "UIScrollViewEx"
require "UILayoutHtml"
require "gamestring"
require "FactoryAnimation"
require "FactoryGameSprite"
require "ChannelProxy"

require "AudioEngine"
require "CCBReaderLoad"

require "KeywordShield"
require "Timer"

require "LogicTable"
require "ResourceManager"
require "EventDef"
require "EventDispatcher"
require "ByteArray"
require "NetHelper"
require "NetSendLoadLayer"
require "NetReConnectLayer"
require "NetHttp"
require "NetLogic"
require "Toast"
require "SystemTime"

require "GameConstconfig"
require "fourFrames"
require "ModelBackpack"
require "ModelSkill"
require "ModelMonster"
require "ModelPlayer"	
require "ModelEquip"
require "ModelGem"
require "ModelPower"

require "LayerAbstract"
require "LayerRoleChoice"
require "chooseServerDataCache"
require "LayerChooseServer"

require "LayerRegister"
require "LayerRegisterProtocal"
require "LayerLoginOwn"
require "LayerLoginChannel"
require "LayerBegin"

require "loginDataCache"
require "LayerMain"
require "LayerLevelSeclet"
require "LayerFightOver"
require "LayerFightReward"
require "LayoutComfigDialog"
require "LayerTowerbg"
require "LayerTowerSettle"
require "LayerPauseGame"
require "GameFightInfo"
require "BackpackLogic"
require "LayerConfirmDialog"
require "LayerSell"
require "LayerEquipBody"
require "LayerBag"


--require "LayerEquipInfo_01"
--这些是需要注释掉的？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
--require "LayerStrengthen"
--require "LayerGemInlay"
--require "LayerGemInfo_01"

require "LayerEquipInfo_03"
require "LayerGemCompound"
require "LayerGemInfo_02"

require "LayerBagSkill"
require "LayerPlayerInfo"
require "LayerTempBackpack"
require "LayerItemInfo_01"
require "LayerItemInfo_02"
require "LayerEquipPut"
require "LayerEquipNoPut"

--各个界面的详细信息
require "LayerJobInfo"
require "LayerEquipInfo_02"
require "LayerGemInfo"
require "LayerItemInfo"
require "LayerSkillInfoLong"
require "LayerSkillFragInfoLong"


require "LayerBackpack"
require "LayerMainEnter"
require "LayerJJcFail"
require "LayerJJcSuccess"
require "LayerLvUp"
require "LayerCopy"

require "FriendChat"
require "FriendDataCache"
require "FriendInfo"
require "FriendList"

require "CopyDateCache"
require "LayerTips"
require "LayerFightFailed" 
require "CopyDelockLogic"
require "LayerCopyDelock"

require "TaskLogic"
require "LayerTask"

require "LayerGameRank"
require "LayerGameRankChoice"
require "AssistanceLogic"
require "LayerAssistance"
require "AudioManager"
require "LayerShopMall"
require "LayerScoreShopMall"
require "LayerSetup"
require "LayerRankLists"
require "LayerGameTrain"
require "loadingDoor"
require "LayerGameMatch"



--铁匠铺界面
require "EquipForgeLogic"
require "LayerSmithMain"
require "LayerSmithStrength"
require "LayerSmithGemInlay"
require "LayerSmithRecast"
require "LayerSmithUpgrade"
require "LayerSmithGemInfo"
require "LayerSmithEquipInfo"
require "LayerSmithUpgradeInfo"
--require "LayerEquipForge"
--require "LayerEquipForgeStrengthen"
--require "LayerEquipForgeUpgrade"
--require "LayerEquipForgeExchange"
--require "LayerEquipForgeRecast"

require "DailyAwardLogic"
require "LayerDailyAward"
require "LayertowerPasslayer"
require "LayerActivity"
require "LayerBuyInput"
require "LayerFirstRecharge"
require "FirstRechargeLogic"
require "DailyActivenessLogic"
require "LayerDailyCrazy"
require "LayerDailyCrazyTip"
require "LevelGiftLogic"
require "LayerLevelGift"
require "LayerFriendPoint"
require "FriendPointLogic"
require "LayerGetCoin"
require "GetCoinLogic"
require "DiscountRestrictionLogic"
require "LayerDiscountRestriction"

require "GM"
require "LayerGameMatch"
require "LayerSweep"
require "BlessLogic"
require "LayerBless"
require "LayerMonsterInfo"
require "LayerSweepTimes"
require "UIMonsterIntroduce"
require "MiltitaryLogic"
require "LayerMiltitary"
require "LayerRecharge"
require "OnlineRewardLogic"
require "LayerOnlineReward"
require "LayerCommodityConvert"
require "layerRoleUp"
require "layerVipGradeGift"
require "LayerVip"
require "layerActivalReward"
require "MailLogic"
require "LayerMail"
require "LayerChenallBoss"
require "layerthreedesc"
require "LayerTipFunction"
require "MonthCardLogic"
require "LayerMonthCard"
require "LayerMonthCardNo"
require "LayerActivityCopyGroup"
require "LayerActivityCopy"
require "LayerCombatLog"
require "LayerMissionComplete"
require "LayerActivityCopyTip"
require "LayerChat"

require "LayerInviteCode"
require "LayerInviteCodeOldFriend"
require "LayerInviteCodeNewNoFriend"
require	"LayerInviteCodeNewFriend"
require	"LayerInviteCodeInput"
require	"LayerInviteCodeHelpItem"
require	"LayerInviteCodeTip"
require "LayerSocialContactEnter"
require "LayerRoleInfo"
require "LayerOneKeyCompletion"
require "LayerRune"
require "LayerSkillMain"
require "LayerSkillDevelop"
require "LayerSkillInfo"
require "LayerSkillFragInfo"
require "LayerSkillUnlock"
require "LayerSkillEquip"
require "LayerSkillGroup"
require "LayerSkillTakeoff"
require "LayerSkillPuton"
require "LayerRuneReward"
require "ItemOutput"

require "LayerRoleTalent"
require "LayerRoleTalentActive"
require "LayerRoleTalentNoActive"
require "LayerRoleTalentReset"
require "RoleTalentLogic"
require "LayerShopBuy"
require "LayerMore"
require "LayerNotice"
require "LayerNoticeActivity"
require "LayerNoticeUpdate"
require "LayerNoticeDetail"
require "ActivityNoticeLogic"
require "LayerPowerHp"
require "LayerContact"
require "LayerRuneShow"
require "LayerGroupMatchFailure"
require "LayerGroupMatchVictory"
require "LayerSpringActivity"
require "LayerSpringDraw"
require "LayerSpringRecharge"
require "SpringActivityLogic"

-- 新支付界面
require "LayerPayByEmoney"
require "LayerPayByRMB"

require "LayerGameMedal"

-- UI界面放在UIManager之前
require "UIManager"

require "ExpressionParse"
require "Class"
require "FightDateCache"
--require "Gamebackgroundlayer"
require "FightRequire"
require "FightConfig"	
--require "GameFightOpenEvent"
--require "GameScenelayer"
require "swallowEventLayer"
require "FightMgr"

require "BattleDialog"
require "TipModule"
require "GuideMgr"
require "LuaAction"
require "TipFunction"
require "TipView"
require "CopyLogic"
require "MessageMgr"
require "ChatLogic"
require "NoticeLogic"
require "SkillLogic"
require "TimeLimitRewardLogic"

require "RemoteDebug"
